language: node_js
  node_js:
    - "8"

  branches:
    only:
      - master
      
  before_install:
    - cd 'FABI-Web'

  before_script:
    - npm install -g @angular/cli

  script:
    - ng lint
    - ng build --prod --aot